### ISSUE TITLE
QUESTION: Different position of ... in colAvgsPerRowSet() and rowAvgsPerColSet()

### ISSUE THREAD

**Issue by PeteHaitch** [HenrikBengtsson/matrixStats#110]
```R
> args(matrixStats::colAvgsPerRowSet)
function (X, W = NULL, cols = NULL, S, FUN = colMeans, tFUN = FALSE, ...) 
NULL
> args(matrixStats::rowAvgsPerColSet)
function (X, W = NULL, rows = NULL, S, FUN = rowMeans, ..., tFUN = FALSE) 
NULL
```

Any reason `tFUN` appears after `...` in `rowAvgsPerColSet()`, Henrik? Would you be amenable to reconciling these (I prefer the argument order of `colAvgsPerRowSet()` for reasons I can elaborate on).

**Comment by HenrikBengtsson** [comment]
There might have been a reason; I'll try to think about it during the day.

**Comment by HenrikBengtsson** [comment]
Just a quick note; the reason for `...` being before `tFUN`, i.e. `FUN, ..., tFUN`, is (most likely) to somewhat clarify that those arguments goes with the call to `FUN`, whereas `tFUN` doesn't.  I use that in several of my packages.  Now, that doesn't explain the difference betweeen col- and row-; I need to see if there was a reason for that.  I cannot see why it should be, so most likely I'll change so they're the same.

**Comment by HenrikBengtsson** [comment]
Ok, following the history of these functions, I can not see a reason why there should be a difference.  I think it's just a mistake.  I made the argument order of `colAvgsPerRowSet()` the same as `rowAvgsPerColSet()`.

**Comment by PeteHaitch** [comment]
Thanks, Henrik!
