### ISSUE TITLE
Plans for next release of matrixStats?

### ISSUE THREAD

**Issue by PeteHaitch** [HenrikBengtsson/matrixStats#114]
Hi Henrik,

I've just submitted https://github.com/PeteHaitch/DelayedMatrixStats to Bioconductor (https://github.com/Bioconductor/Contributions/issues/514). Obviously, it depends heavily on **matrixStats**. I have been developing against the 'develop' branch of **matrixStats**, largely because of https://github.com/HenrikBengtsson/matrixStats/issues/110. 

Do you have any plans on sending an updated version of **matrixStats** to CRAN? Obviously, it's a relatively low-priority for most users of **matrixStats** but is a bit of a blocker for me at the moment (though I can come up with a temporary work around if needed).

Cheers,
Pete

**Comment by HenrikBengtsson** [comment]
See the 'Next release' milestone at https://github.com/HenrikBengtsson/matrixStats/milestones.  The show-stopper for a quick release is Issue #105, which needs some serious work / thoughts.

**Comment by PeteHaitch** [comment]
Thanks! I will try to spend some time on #105 but it won't be in the next few days. No matter, I will workaround #110 for the initial submission to BioC

**Comment by HenrikBengtsson** [comment]
thanks, the more eyes/brain cycles we can get on #105 the better. I just wanna make sure to get a stable API also there - behavior has already changed once in the past.

**Comment by HenrikBengtsson** [comment]
ah, now I see - there's a deadline for the next round. could you skip #110 from you API? I wouldn't consider it to be essential - those functions are even on the border of being outside of the matrixStats scope.

**Comment by PeteHaitch** [comment]
Yeah, I think for now I will omit #110 from the API. Thanks for the prompt response!
