### ISSUE TITLE
Documentation: Add Cumulative functions to vignette

### ISSUE THREAD

**Issue by Henrik-P** [HenrikBengtsson/matrixStats#12]
It would be nice if also 'the cumulative functions' (`?rowCumsums`) were included in [the vignette](http://cran.r-project.org/web/packages/matrixStats/vignettes/matrixStats-methods.html).

**Comment by HenrikBengtsson** [comment]
Thanks for this; I forgot to add those.  It's been fixed in the 'develop' branch, which will become the next release.
