### ISSUE TITLE
Question on interpolate parameter in weightedMedian()

### ISSUE THREAD

**Issue by dcowen4** [HenrikBengtsson/matrixStats#125]
I have a question regarding the weightedMedian() function in the matrixStats package in R. In particular, I would be interested in some further details on how the interpolate parameter in the function works. 

I am fairly new to the concept of a weighted median but as I understand it, if interpolate = False, the function will return one of the observations in the vector x, or the average/weighted average between two x's that satisfy the criteria, where the partition of weights is closest to 0.5 (or S/2). Am I correct in assuming that the interpolate parameter will give a value that is not necessarily in x, where the partition is exactly 0.5?

I have had trouble replicating the interpolate functionality with other methods. As an example, the article on the weighted median in Wikipedia (https://en.wikipedia.org/wiki/Weighted_median) contains the following example:

x <- c(1,2,3,4) 

w <- c(0.49,0.01,0.25,0.25). 

The call weightedMedian(x, w, interpolate = F) gives a result of 2.5, as expected. 

The call weightedMedian(x, w, interpolate = T) gives a result of 2.038462. 

When attempting to find the weighted median by directly minimizing the function mentioned in the description of the weighted median function, using the same x and w as above I get:

A <- data.frame(cbind(x,w))

wm <- function(data,par){
  with(data, sum(w*abs(x-par)))
}

result <- optim(par = (min(x)), fn = wm, data = A, method = "Brent", lower = min(x), upper = max(x))

Here result$par gives a value of 2.145898, which is also not one of the observations in x. Is the difference due to a different algorithm for the optimization, or should I now apply some sort of linear interpolation to arrive at 2.038462?

**Comment by HenrikBengtsson** [comment]
The following are the estimates provided my `matrixStats::weightedMedian()`:
```r
> x <- c(1, 2, 3, 4)
> w <- c(0.49, 0.01, 0.25, 0.25)
> matrixStats::weightedMedian(x, w = w, interpolate = TRUE) # default
[1] 2.038462
> matrixStats::weightedMedian(x, w = w, ties = "weighted")
[1] 2.5
> matrixStats::weightedMedian(x, w = w, ties = "mean")
[1] 2.5
> matrixStats::weightedMedian(x, w = w, ties = "min") # "lower weighted median"
[1] 2
> matrixStats::weightedMedian(x, w = w, ties = "max") # "upper weighted median"
[1] 3
```

The paragraph on the `ties` argument in `?matrixStats::weightedMedian` should describe how they differ and how they're calculated.  In the next version (commit adb34e6), the help will mention "lower" and "upper" weighted medians too.

I don't know the details, but my guess would be that `optim(..., method = "Brent")` does some type of interpolation when there is not a unique solution.

Hope this help

**Comment by dcowen4** [comment]
Many thanks for your answer. Indeed the section and logic behind the ties argument is clear. 

I found this description of what is "under the hood" of the weightedMedian(), which is very useful https://stat.ethz.ch/pipermail/r-help/2002-February/018614.html. However, it is from a version that doesn't have the interpolate parameter. Would you happen to have similar documentation with the interpolate included?

**Comment by HenrikBengtsson** [comment]
I've [added a paragraph](https://github.com/HenrikBengtsson/matrixStats/commit/d0a58961c0f994dc5c49f955928a65b5e578915a) explaining that the linear interpolation estimate is a weighted mean of the two "tied" values.  Hope this helps.

**Comment by dcowen4** [comment]
Yes, indeed now I see how it works and I am able to replicate the result of the function. Many thanks for your help!

**Comment by MichaK11** [comment]
First of all, thank you very much for your work on the package.

I found a case where I do not understand what the package is actually calculating. Could you please give some insight in what the calculation looks like?

I have the following data set:

id | x | w
------------ | ------------- | -------------
1 | -0.103 | 0.08
2 | -0.089 | 0.14
3 | 0 | 0.22
4 | 0 | 0.12
5 | 0.039 | 0.28
6 | 0.055 | 0.16


The weightedMedian should be 0 as row no. 4 has a cumulative weight with 0.5 and x equals 0. However, weightedMedian(x,w) gives 0.0078.

If I slightly change the weights such that id=4 has a w of 0.125 and id=6 has a w of 0.155, weightedMedian should interpolate between the x of id=3 and id=4. As both of them are 0 I expect the result to be 0 as well. However, the result is 0.00702.
