### ISSUE TITLE
Logical matrix 

### ISSUE THREAD

**Issue by muschellij2** [HenrikBengtsson/matrixStats#139]
## Description of Error
In `rowCumsums`, you cannot have a logical matrix, which should work.  See here we can pass in an integer data and it works fine:
``` r
library(matrixStats)
mat = matrix(rnorm(10*1000), ncol = 10)
head(rowCumsums((mat > 0) * 1))
#>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
#> [1,]    1    2    3    3    3    3    3    4    4     5
#> [2,]    0    1    1    1    2    2    3    4    4     4
#> [3,]    1    2    2    2    2    2    2    3    3     3
#> [4,]    0    0    1    1    1    2    2    2    3     4
#> [5,]    0    0    1    1    1    2    3    3    3     4
#> [6,]    0    0    0    1    1    1    1    2    3     4
```

But when we pass in a logical matrix, this does not work:
``` r
rowCumsums(mat > 0)
#> Error in rowCumsums(mat > 0): Argument 'x' cannot be logical.
```

<sup>Created on 2018-12-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by HenrikBengtsson** [comment]
I think it makes to support logical input also in this case. I suspect it's not too complicated to add this.  I've added it to the 'Next Release' milestone.

**Comment by HenrikBengtsson** [comment]
This has been [fixed in the develop branch](commit/ceb6a0) and will be part of the next release.

**Comment by HenrikBengtsson** [comment]
matrixStats 0.55.0 is now on CRAN
