### ISSUE TITLE
Use of `return()` in `rowMeans2()` ?

### ISSUE THREAD

**Issue by Eluvias** [HenrikBengtsson/matrixStats#143]
Given `matrixStats` coding standards, is the use of `return()` on this occasion intentional?

```r
body(matrixStats::rowMeans2)

{
    dim. <- as.integer(dim.)
    na.rm <- as.logical(na.rm)
    has_nas <- TRUE
    return(.Call(C_rowMeans2, x, dim., rows, cols, na.rm, has_nas, 
        TRUE))
}
```

**Comment by HenrikBengtsson** [comment]
Hi, thanks for making us aware of this. That's a mistake - no need for a `return()` there.  I've removed this for the next release (develop branch).
