### ISSUE TITLE
[DOCS] - `rowRanks()` has a missing  part in return value description

### ISSUE THREAD

**Issue by cgiachalis** [HenrikBengtsson/matrixStats#144]
Hi - 

Here is the description of return value; check the last bit `for double()`...

![image](https://user-images.githubusercontent.com/26255858/55296648-55f96e80-5414-11e9-813f-10e4e2b7e865.png)

Taken from: https://www.rdocumentation.org/packages/matrixStats/versions/0.54.0/topics/rowRanks

The problem seems to be in lines 47-48:

![image](https://user-images.githubusercontent.com/26255858/55296687-e8017700-5414-11e9-84be-0b6344f122a7.png)

Thanks

**Comment by cgiachalis** [comment]
Also in the `ties.method` description, it says *`A character string specifying how ties are treated. For details, see below.`*

But there is no explanation in Details about how ties are treated.

We can point to base `rank` instead, 
e.g. *`A character string specifying how ties are treated. For details, see rank().`*

**Comment by HenrikBengtsson** [comment]
Note to self: This is related to PR #146.

**Comment by HenrikBengtsson** [comment]
Fixed in the develop branch. Thxs for reporting.
