### ISSUE TITLE
Inconsistent behavior with all NA argument 

### ISSUE THREAD

**Issue by gdemin** [HenrikBengtsson/matrixStats#145]
I understand that in the cases below we have different types - integer and logical. But behavior with all NA argument looks very confusing.
```R
library(matrixStats)
vec = c(1, NA)
weightedMean(vec, na.rm = TRUE)
# [1] 1
```
In the case below I would expect NA or NaN as a result. 
```R
vec = c(NA, NA)
weightedMean(vec, na.rm = TRUE)
# Error in weightedMean(vec, na.rm = TRUE) : 
#     Argument 'x' cannot be logical.
```

**Comment by HenrikBengtsson** [comment]
It's because `NA` is actually a logical. The numeric version is `NA_real_`.

When you use `c(NA, 1)`, the `1` will force coercion to numeric so the first element becomes `NA_real_`.

**Comment by HenrikBengtsson** [comment]
Or did you propose a more informative error message? If so,    any suggestions how had should work?

**Comment by HenrikBengtsson** [comment]
Ah... I shouldn't reply from the phone while walking - was hoping to get clarity while I had you online.  I see that you propose/expect:

>  "... NA or NaN as a result."

We don't want to do that for the same reason we don't want:

```r
weightedMean("hello")
```
or
```r
weightedMean(NA_character_, na.rm = TRUE)
```
to return something other than producing an error.

By design, almost all functions in matrixStats accept only integer and numeric input.  Everything else is considered a programming/user mistake that should be caught as soon as possible.

PS. There are some feature requests (e.g. Issue #139) for open up for logical input as well when such values can be interpreted as zero-one values, i.e. `x_integer <- as.integer(x_logical)`.  That might happen, but we have to be careful not to open up Pandora's box.  Being very conservative can help prevent mistakes from silently pass through analytical pipelines.

**Comment by gdemin** [comment]
It will be wonderful if matrixStats would support logical arguments.
I work with data with a lot of missings and it is quite easy to get NA_logical instead of the numeric value during data transformation. For example, via `ifelse`:
```R
# some elements are NA - we get numeric
class(ifelse(c(8, NA)>5, 1, 2)) # weightedMean - ok
# [1] "numeric"
# the same expression and numeric argument but we have logical
class(ifelse(c(NA_integer_, NA_integer_)>10, 1, 2)) # weightedMean - error
# [1] "logical"
```
It will be very convenient if we would have consistent NA propagation.

**Comment by HenrikBengtsson** [comment]
Wow, I didn't know about that "oddity" of `ifelse(test, yes, no)`, but, like a lot of things, it is indeed documented in `help(ifelse)`.  I do understand that it's API does not allow for a default type and it does not want to evaluate `yes` and `no` to find out (and those can be different anyway).  There should really be an optional `mode` argument, e.g.
```r
y <- ifelse(test, yes, no, mode = "numeric")
```
which could default to `mode = NULL` for backward compatibility.  Oh, well, this is not the place to propose that.

So, I understand your needs, but I don't think it's not really matrixStats's task to provide "automagic" workarounds for upstream misdesign/misspecification.  I recommend using:
```r
as.numeric(ifelse(x > 5, 1, 2))
```
when there's a risk that `x` may be all missing values.  The overhead of using `as.numeric(z)` when `z` is already numeric is near zero.

If matrixStats would open up the door of trying to second guess the intent of the input data and automatically recover for these type of corner cases, we'd most likely just introduce another set of odd corner cases that can be produced in R.

**Comment by HenrikBengtsson** [comment]
FYI, there was another related request in #162.  In next release, `weightedMean()` and `weightedMedian()`, plus their matrix counterpart functions, support logical input, which means the example in your top comment now works as you'd expect, i.e.

```r
> y <- matrixStats::weightedMean(c(NA_real_, NA_real_), na.rm = TRUE)
> str(y)
 num NaN

> y <- matrixStats::weightedMean(c(NA_integer_, NA_integer_), na.rm = TRUE)
> str(y)
 num NaN

> y <- matrixStats::weightedMean(c(NA, NA), na.rm = TRUE)
> str(y)
 num NaN
```
