### ISSUE TITLE
Negative diff arguments for xxxDiff() should throw error

### ISSUE THREAD

**Issue by const-ae** [HenrikBengtsson/matrixStats#158]
Hi Henrik,

I think it would be better and more consistent if `varDiff()`, `sdDiff()`, `madDiff()` and `iqrDiff()` would return an error if the `diff` argument is smaller than zero.

``` r
library(matrixStats)
tmp <- rnorm(10)
diff2(tmp, diff = -3)
#> Error in diff2(tmp, diff = -3): Argument 'differences' must be a positive integer.
varDiff(tmp, diff = -3)
#> [1] 3.008179
sdDiff(tmp, diff = -3)
#> [1] 1.73441
madDiff(tmp, diff = -3)
#> [1] 1.334602
iqrDiff(tmp, diff = -3)
#> [1] 1.566585
```

<sup>Created on 2019-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Best, Constantin

**Comment by HenrikBengtsson** [comment]
Thxs. Makes sense.

**Comment by HenrikBengtsson** [comment]
Fixed in develop version. We now get an error:
```r
> matrixStats::varDiff(1:3, diff = -3)
Error in matrixStats::varDiff(1:3, diff = -3) : 
  Argument 'diff' must be non-negative: -3
```

**Comment by HenrikBengtsson** [comment]
FYI, matrixStats 0.56.0 with this bugfix is now on CRAN.
