### ISSUE TITLE
weighted* for logical x raises error

### ISSUE THREAD

**Issue by mayer79** [HenrikBengtsson/matrixStats#162]
I was recently stumbling over the weighted* functions with logical input:

```
weightedMean(1:10 > 5) # Error
weightedMedian(1:10 > 5) # Error
weightedVar(1:10 > 5) # Works
```
Would it be possible to catch this case in an efficient way?

**Comment by HenrikBengtsson** [comment]
Thanks for reporting.  For the record/clarification:
```r
> weightedMean(1:10 > 5)
Error in weightedMean(1:10 > 5) : Argument 'x' cannot be logical.

> weightedMedian(1:10 > 5)
Error in weightedMedian(1:10 > 5) : Argument 'x' cannot be logical.

> weightedVar(1:10 > 5)
[1] 0.2777778
```

Q. Is this a request for `weightedVar()` to also give an error, or is it a request for supporting weighted mean/median on logical input?

**Comment by mayer79** [comment]
Hello Henrik, thanks for responding. I'd prefer a version for logical input, like `stats::weightedMean` or `mean`.

**Comment by HenrikBengtsson** [comment]
FYI, support for logical input to `weightedMean()`, `weightedMedian()`, and their counterpart row- and column-based functions has been added to the 'develop' branch (= next release).
