### ISSUE TITLE
matrixStats for dgcMatrix

### ISSUE THREAD

**Issue by kanupolo10** [HenrikBengtsson/matrixStats#164]
Hi Henrik,

Great resource for matrix stats...is there any plans to implement these functions for sparse matrices? I understand that these functions are implemented for DelayedArrays, so that is an alternative...but may R packages do not support these arrays but do seem to support sparse matrices. 

Best,
--Tony

**Comment by PeteHaitch** [comment]
Hi Tony,

There's work towards this in https://github.com/const-ae/sparseMatrixStats.

Cheers,
Pete

**Comment by hpages** [comment]
And that work is now completed and available in Bioconductor (has been since April 28, 2020): https://bioconductor.org/packages/sparseMatrixStats

Best,
H.

**Comment by kanupolo10** [comment]
Thanks all!
