### ISSUE TITLE
Bug in rowCollapse if combined with row subsetting

### ISSUE THREAD

**Issue by const-ae** [HenrikBengtsson/matrixStats#170]
Hi Henrik,

I think I found a bug in `rowCollapse` if it is combined with row subsetting:

``` r
mat <- matrix(1:15, nrow = 5, ncol = 3)
print(mat)
#>      [,1] [,2] [,3]
#> [1,]    1    6   11
#> [2,]    2    7   12
#> [3,]    3    8   13
#> [4,]    4    9   14
#> [5,]    5   10   15
matrixStats::rowCollapse(mat, idxs = 2)
#> [1]  6  7  8  9 10
matrixStats::rowCollapse(mat, idxs = 2, rows = 1:4)
#> [1]  6 NA NA NA
matrixStats::rowCollapse(mat, idxs = rep(2, 5), rows = 1:4)
#> [1] 6 7 8 9
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
I would expect the last two lines to do the same.

I think the problem is [here](https://github.com/HenrikBengtsson/matrixStats/blob/develop/R/rowCollapse.R#L41) where the `idxs` vector is subset. This works well if `idxs` has `nrow(mat)` elements, but returns `NA` if `rows` is longer than `idxs`.

If you want, I can draft a quick PR to fix the issue.

**Comment by HenrikBengtsson** [comment]
Thxs. Fixed for next release.

**Comment by HenrikBengtsson** [comment]
BTW, this is a good example where full-coverage unit tests != solid system tests.  Forgot to test the combination of `idxs` and subsetting.
