### ISSUE TITLE
colAvgsPerRowSet fails on input with a single column

### ISSUE THREAD

**Issue by const-ae** [HenrikBengtsson/matrixStats#172]
Hi Henrik,

If I call `colAvgsPerRowSet()` with a matrix that has a single column the function throws an error. It works when the input has two or more columns or zero columns:

``` r
library(matrixStats)
mat <- matrix(1:12, ncol = 2)
S <- cbind(1:2, 3:4, 5:6)
print(mat)
#>      [,1] [,2]
#> [1,]    1    7
#> [2,]    2    8
#> [3,]    3    9
#> [4,]    4   10
#> [5,]    5   11
#> [6,]    6   12
print(S)
#>      [,1] [,2] [,3]
#> [1,]    1    3    5
#> [2,]    2    4    6
colAvgsPerRowSet(mat, S = S, FUN = colSums2)
#>      [,1] [,2]
#> [1,]    3   15
#> [2,]    7   19
#> [3,]   11   23

mat_zero_column <- matrix(numeric(0), nrow = 6, ncol = 0)
print(mat_zero_column)
#>     
#> [1,]
#> [2,]
#> [3,]
#> [4,]
#> [5,]
#> [6,]
colAvgsPerRowSet(mat_zero_column, S = S, FUN = colSums2)
#>     
#> [1,]
#> [2,]
#> [3,]

mat_single_column <- mat[,1,drop=FALSE]
print(mat_single_column)
#>      [,1]
#> [1,]    1
#> [2,]    2
#> [3,]    3
#> [4,]    4
#> [5,]    5
#> [6,]    6
colAvgsPerRowSet(mat_single_column, S = S, FUN = colSums2)
#> Error in dim(Z) <- c(length(Z), nbrOfSets): dims [product 9] do not match the length of object [3]
```

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I believe the fix would be to change this [line](https://github.com/HenrikBengtsson/matrixStats/blob/develop/R/rowAvgsPerColSet.R#L135) from
`dim(Z) <- c(length(Z), nbrOfSets)` to `dim(Z) <- c(dimX[1L], nbrOfSets)`

Best, Constantin

**Comment by HenrikBengtsson** [comment]
Ah... I've just finished two-days of preparing to submit matrixStats 0.57.0 to CRAN and I forgot/missed this one.  I'm planning on taking some time off next so I don't have time to fix this one and redo all validation including revdepcheck.  Also, if I don't submit what I have now, there's is a risk that it'll be a while again before I have time to pre a submission for the R-devel version available at the time.  So, I'll go ahead with what I have.  Hopefully `colAvgsPerRowSet()` is not that commonly used for this to be a high-priority bug.

**Comment by HenrikBengtsson** [comment]
@const-ae, would you mind creating a PR for this?  If you could include a test for it as well, that would be great.

**Comment by const-ae** [comment]
I created a [PR](https://github.com/HenrikBengtsson/matrixStats/pull/194). 

Sorry for the delay, I got a bit swamped last week.

**Comment by HenrikBengtsson** [comment]
Brilliant. Thxs

**Comment by HenrikBengtsson** [comment]
Merged. Thank you.
