### ISSUE TITLE
[DOC] - Revert to previous function formatting (roxygen)

### ISSUE THREAD

**Issue by Eluvias** [HenrikBengtsson/matrixStats#173]
With roxygen2 v0.7.0 the default formatting for function usage has changed. See screenshots below.

The new default can be very annoying in cases where a function has many inputs or when we document multiple functions.

In case you want to revert back to previous default formatting, here is how:
-  add in  DESCRIPTION file : `Roxygen: list(old_usage = TRUE)`  .

Thanks.

![image](https://user-images.githubusercontent.com/22600883/77939256-cf899e00-72ae-11ea-896f-7a8ee878fceb.png)

![image](https://user-images.githubusercontent.com/22600883/77939781-96056280-72af-11ea-8b59-f612259dcb2f.png)

**Comment by HenrikBengtsson** [comment]
Thanks for letting me know about the roxygen setting, which I wasn't aware of.  I'm happy to revert to the old style.

**Comment by HenrikBengtsson** [comment]
Done for next release. Currently in develop branch.

**Comment by Eluvias** [comment]
Thank you!
