### ISSUE TITLE
Inconsistent behavior of colAnys() / colAlls() if value = FALSE

### ISSUE THREAD

**Issue by const-ae** [HenrikBengtsson/matrixStats#177]
Hi Henrik,

I think I found a bug in `colAnys()` and `colAlls()` if `value = FALSE`. In the documentation you say

> When value is logical, the result is as if the function is applied on as.logical(x)

However, this only applies if `value = TRUE`. If `value = FALSE` all values different from `1` are treated as `FALSE`:

``` r
mat <- matrix(0, nrow = 6, ncol = 5)
mat[,1] <- 1:6
mat[,2] <- 1
mat[3,3] <- 42
mat[,4] <- 11:16
mat[2,4] <- NA
mat
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    1    1    0   11    0
#> [2,]    2    1    0   NA    0
#> [3,]    3    1   42   13    0
#> [4,]    4    1    0   14    0
#> [5,]    5    1    0   15    0
#> [6,]    6    1    0   16    0
lgl_mat <- array(as.logical(mat), dim(mat))
lgl_mat
#>      [,1] [,2]  [,3] [,4]  [,5]
#> [1,] TRUE TRUE FALSE TRUE FALSE
#> [2,] TRUE TRUE FALSE   NA FALSE
#> [3,] TRUE TRUE  TRUE TRUE FALSE
#> [4,] TRUE TRUE FALSE TRUE FALSE
#> [5,] TRUE TRUE FALSE TRUE FALSE
#> [6,] TRUE TRUE FALSE TRUE FALSE

# value == TRUE works
matrixStats::colAnys(mat, value = TRUE)
#> [1]  TRUE  TRUE  TRUE  TRUE FALSE
matrixStats::colAnys(lgl_mat, value = TRUE)
#> [1]  TRUE  TRUE  TRUE  TRUE FALSE


# value = FALSE treats x unequal 1 as FALSE
matrixStats::colAnys(mat, value = FALSE)
#> [1]  TRUE FALSE  TRUE  TRUE  TRUE
matrixStats::colAnys(lgl_mat, value = FALSE)
#> [1] FALSE FALSE  TRUE    NA  TRUE
matrixStats::colAnys(mat == 1, value = FALSE)
#> [1]  TRUE FALSE  TRUE  TRUE  TRUE

# For brevity, I only show colAnys(), but the same is true for colAlls()
```

<sup>Created on 2020-05-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This problem was already brought up in #89, however the fix solves the problem only partially.
If you want, I could try and draft a PR to fix the problem.

Best, Constantin

**Comment by HenrikBengtsson** [comment]
Hi, sorry for the delay.  Thanks for this. Yes, the `value = FALSE` results look like a bug to me.

Yes, a PR would be much appreciated and we take it from there.  Please make sure to avoid coercing or copying `x`.

**Comment by const-ae** [comment]
I created a PR https://github.com/HenrikBengtsson/matrixStats/pull/179

**Comment by HenrikBengtsson** [comment]
Brilliant, thank you.

Could you please also add a PR for DESCRIPTION, adding yourself as a contributor to the package?

**Comment by const-ae** [comment]
New PR at https://github.com/HenrikBengtsson/matrixStats/pull/181. Thanks :)
