### ISSUE TITLE
WISH: Should support for data.frame:s be added?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#18]
There is clearly a need/wish to do perform matrixStats-like computations on data.frame:s. 

Although they are also tabular/rectangular shaped, data.frame:s are very different from matrices in what they contain and how they are represented.  Simply speaking, a `data.frame` is a `list` of a number elements (=`ncol(df)`), where all elements are of equal lengths (=`nrow(df)`). Further more, the columns in a data.frame can be of different types.

I had this as a to-do item for quite a while, it's not really clear to me whether it belongs to the matrixStats package or not and also not whether there is much of a gain of just passing `as.matrix(df)`.  This issue/thread can serve as an open discussing and for identifying pro's and con's.

UPDATE (2015-06-05): To clarify, yes, there was some sporadic support for data.frame:s for some functions of matrixStats in the past, but they we're not really part of the plan.  Please also not that it's only recently that matrixStats is starting to find it's true identity: highly optimized low-level function with minimal overhead in calling, asserting arguments etc.  This is why we also move away from S3 and S4 dispatching and focus on the most fundamental R data types.

## PROS
* It's convenient to be able to do things such as `colMedians(df)`.
* Special implementation for data.frame:s avoids having to create an temporary matrix - as in  `colMedians(as.matrix(df))` - which is more memory efficient.  On the other hand, it's probably hard to beat a simple `dfS <- lapply(df, FUN=median)`.

## CONS
* It's more natural to calculate summaries/statics column by column, than row by row.
* What should be returned?  A `data.frame` or a `matrix`?
 - What should `rowMedians(df)` return when, say, 4 columns are integers, 2 are doubles and 3 are logical?
 - What should `rowMedians(df)` return when, say, 4 columns are integers and 2 are character strings?
* What should `colMedians(df)` calculate when the first column contains, say, character names?

**Comment by muschellij2** [comment]
Agreed.  I just ran into some errors in code when I upgraded matrixStats and you implemented S4 and figured I'd contribute if you wanted.

**Comment by hcorrada** [comment]
I don't think it's worth it for the following two reasons:

1) I think the big gains in efficiency in matrixStats is that we can make assumptions about types and shapes for matrices, which we can't do for data.frames.

2) dplyr has a decent number of efficiently implemented summary statistics for data.frame-like objects.

Thoughts?

**Comment by HenrikBengtsson** [comment]
I think there's certainly some similar type of speedup we can do column-by-column in data.frame:s, e.g. by inspecting data type (integer or double etc.).   But in general I tend to agree with you that it is of low priority to add support for data.frame:s.

BTW, doing row-wise computations on data.frame:s is just a poorly defined problem in general, but it is possible that one can consider it a well-defined problem if done a specific subset of columns, e.g. student's total test score across a set of numeric "test_score" columns.  Also here one could gain from optimizing for data type etc.  But again, low priority.

I'm keeping this issue open for display and in case someone wants to comment on pros and cons.

**Comment by muschellij2** [comment]
I agree in principle, but my main concern was that before S4 classes were
updated running operations on data.frames worked, then after the update
they didn't.  In that regard, I just wanted to discuss backwards
compatibility.

Also, colMeans and colSums works on data.frames, simply with the code:

    if (is.data.frame(x))

        x <- as.matrix(x)

so I wanted to discuss the possibility of consistency.  I understand
colMeans/Sums is in base, but a novice user may not understand why colMeans
works in base but colSds would not.

Again however, is that I agree with low priority.

Thanks for the good discussion.

On Mon, Mar 30, 2015 at 12:31 PM, Henrik Bengtsson <notifications@github.com

**Comment by muschellij2** [comment]
Is that you Hector?  I didn't notice until now with the handle.  Hope all is well!

**Comment by HenrikBengtsson** [comment]
Thanks for the feedback. I'm closing this, because:

I strongly believe matrixStats should focus on matrices of integer and double data types (and possibly others such as logicals and even characters).   Although they may look very similar, particularly the column-wise functions, data.frames are completely different creatures to plain matrices. For instance, their storage models are different, i.e. they are stored as named lists and not as contiguous elements in memory.  There are also several corner cases that needs to be taken care of when working with data frames, which I mention my the top comment.  As @hcorrada also says, there are/will probably be better alternatives for working with data frames.

Finally, I'd argue that it is a good thing to have to explicitly coerce to a matrix in code/scripts, e.g. `rowMedians(as.matrix(df))`.  This makes it very clear that there is an expensive coercion going on.  Sure, it might nice to be able to write `rowMedians(df)` at the prompt, but I think I (we?) can live with that.
