### ISSUE TITLE
API: Names attribute is neither well defined nor guaranteed

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#190]
This is mostly an FYI right now.  

Note that the matrixStats API does _not_ guarantee anything about names, rownames, colnames being returned or not.  For example, there are functions where you might get results with names if you call it with one kind of arguments whereas with other combinations you won't.

Future versions of the matrixStats API might (i) drop names all along, (ii) add names everywhere, or (iii) gain arguments for controlling whether or not names should be returned.

At the moment, please don't make any assumptions about names attributes (e.g. in your package tests).

**Comment by const-ae** [comment]
I think this is a reasonable note of caution. 

> At the moment, please don't make any assumptions about names attributes (e.g. in your package tests).

I currently try to copy the behavior of `matrixStats` in `sparseMatrixStats` and check this with unit tests. Should I remove those?

**Comment by HenrikBengtsson** [comment]
> I currently try to copy the behavior of matrixStats in sparseMatrixStats and check this with unit tests. Should I remove those?

If you can drop the checks on the names attribute, I think that would good.  It would spare you and me some trouble if/when we get to do an overhaul of how name attributes are handled.

**Comment by const-ae** [comment]
Okay, I now do all tests with unnamed matrices. Now, changing the handling of names in `matrixStats` shouldn't break my unit tests.

**Comment by HenrikBengtsson** [comment]
Thanks. I did notice this when update implementation around the `center` argument (e.g. Issue #160) so I decided to make my changes backward compatible with regard to the names attributes (although they'd only show up when `center` was specified). 
So for now, your [Bioc-release package tests](https://github.com/HenrikBengtsson/matrixStats/blob/1b68d5cb946f2c8c86522b2e19837f99cbc7425d/revdep/README.md).

**Comment by yaccos** [comment]
Have you decided yet which approach will be chosen by the future API? Personally, I would prefer solution (ii) "Keep names everywhere" as this is the behavior of the similar functions in the `base::rowMeans` family. Additionally, I think the performance overhead would be neglectable. If solution (i) "Drop names all along" is chosen, I would view it as user-hostile in the cases where you need the names and thus have to add them manually afterwards.

**Comment by HenrikBengtsson** [comment]
Nothing decided; this one will take quite a while to decide on, and then to implement and provide solid testing for.

The matrixStats package was created to maximize performance. One example of when running things such as:

```r
y <- lapply(X, rowMeans)
```
where each element is a teeny matrix;
```r
X <- list()
for (kk in 1:100e6) X[[i]] <- matrix(rnorm(2*4), nrow=2)
```

In those cases, we want to minimize any type of overhead possible. Handling the names attribute might add significant overhead in three cases. Providing an argument will make it possible to enable or disable this handling so everyone can get what they want/need.

Setting the default to add name attributes to the results might penalize existing code bases that counted on it not to happen. So, the default might have to be to disable them by default (which is the closest to hope it works now).

**Comment by yaccos** [comment]
This issue should be updated, names are supposed to be handled consistently using the `useNames` argument as of version 0.60.0

**Comment by HenrikBengtsson** [comment]
Yes, we now have support for names attributes for row- and column-based functions.  These now takes `useNames=TRUE` and `useNames=FALSE`, as well as and `useNames=NA` for backward compatibility (until further notice).  This was implemented through our [GSOC 2021 project](https://github.com/rstats-gsoc/gsoc2021/wiki/matrixStats) that is about to wrap up.

We have also not decided on what the new default should be.  Currently, we stay 100% backward compatible by using `useNames=NA` as the default.  It will be a while before we move forward with changing the default, e.g. there are several reverse package dependencies that need to be updated before we make a change, otherwise they will break.

We have not yet added support for name attributes of vector based functions.  I'll create a new, separate issue for that and will close this one.
