### ISSUE TITLE
weightedMean - potential bug

### ISSUE THREAD

**Issue by Waschoi** [HenrikBengtsson/matrixStats#198]
Hi and many thanks for the great work!

I found relevant difference in them mean/var between your package and base/outher packages:

      tibble::tribble(
     ~b16b1,              ~wph,
          1,  1.34155711131806,
          2,  1.37203810185668,
          1,  1.34155711131806,
          3,  1.30376451721152,
          1, 0.680037448261566,
          2, 0.853061530070061,
          5, 0.581379160588353,
          5, 0.940346387561855,
          2,  1.03522037672934,
          1, 0.975563158485801,
          2,  1.17196788790162,
          4,  1.37203810185668,
          2, 0.581379160588353,
          4,  1.34155711131806,
          5,  1.08098771216558,
          1,  1.71313974371497,
          2,  1.37203810185668,
          2, 0.931651421931088,
          2, 0.538683672957699,
          4, 0.581379160588353
         ) -> data

            data%>%
            summarise_at(vars(b16b1), list(
            mean  = ~weighted.mean(., w = wph, na.rm = T),
            mean2 = ~expss::w_mean(., weight = wph),
            mean3 = ~matrixStats::weightedMean(., weight = wph, na.rm = T, refine = T),
            mean4 = ~sjstats::weighted_mean(x=., weights = wph),
            n = ~n()))

           # A tibble: 1 x 5
           mean mean2 mean3 mean4     n
          <dbl> <dbl> <dbl> <dbl> <int>
            2.46  2.46  2.55  2.46    20
matrixStats::weightedMean gives a different result although expss uses this function for calculation. Do you habe any idea?

**Comment by gdemin** [comment]
Hi @Waschoi, 
For matrixStats there is no `weights` arguments. It's called `w`. `matrixStats::weightedMean(as.double(data$b16b1), w = data$wph)` gives correct result.

**Comment by Waschoi** [comment]
I am so sorry. Than I know tat there es is false implementation in expss :)
