### ISSUE TITLE
Add argument `useNames` also to vector-based functions

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#210]
Since matrixStats 0.60.0, all row- and column-based functions have argument `useNames`.  Next is to add that also to our vector-based functions, where applicable.  For example,

```r
> x <- 1:10
> names(x) <- letters[seq_along(x)]
> x
 a  b  c  d  e  f  g  h  i  j 
 1  2  3  4  5  6  7  8  9 10 

> diff(x)
b c d e f g h i j 
1 1 1 1 1 1 1 1 1 

> matrixStats::diff2(x)
[1] 1 1 1 1 1 1 1 1 1
```

**Comment by yaccos** [comment]
It would be helpful to know which functions this applies to.

**Comment by HenrikBengtsson** [comment]
As part of PR#218, we now got:

```r
> matrixStats::diff2(x)
b c d e f g h i j 
1 1 1 1 1 1 1 1 1
```

I've checked the rest of the API, I cannot find another function that needs `useNames`.
