### ISSUE TITLE
CRAN: Trim down the package test check time

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#211]
The current version, matrixStats 0.60.1, has checks times near or above the 10-minute limit.  As part of the next release, we should try to trim down this.  Doing so will also reduce the risk of having to do a manual intervention during CRAN submission.

**Comment by yaccos** [comment]
Adding naming support included a lot of test cases and these were aggregated in a combinatorial manner (all combinations of cases were tested). Maybe it could be wise to review these test cases and only extract what we actually need. Furthermore, I assume test time could be reduced by investigating issue #212.

**Comment by HenrikBengtsson** [comment]
I've almost halved the check time for the tests by not searching the full grid of (rows, cols, na.rm, useNames, ...), but only (rows, cols) w/ "intelligent" iteration of (na.rm, useNames, ...), cf. https://github.com/HenrikBengtsson/matrixStats/commit/66bd36bea61dc2b3577b080996ea928c470a91ca.

Good enough for now, closing ...
