### ISSUE TITLE
PERFORMANCE: rowSums2 performance degradation

### ISSUE THREAD

**Issue by minemR** [HenrikBengtsson/matrixStats#212]
I noticed performance degradation for `matrixStats` 0.60.1. Approximate two times slower than previous release. Is this expected, as with changes in 0.60.1? On my secondary system, I even saw `base::rowSums` outperform `matrixStats::rowSums2`

```R
library(matrixStats)
library(bench)

nr <- 1000
nc <- 20

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
dim(x)

br <- mark(rowSums = rowSums(x),
           rowSums2 = rowSums2(x),
           rowSums2_noNames = rowSums2(x, useNames = F))
br[, 1:7]

# 0.60.0
#   expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
#   <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
# 1 rowSums            47.6us   48.3us    20406.    7.86KB     4.11  9933
# 2 rowSums2             18us   19.1us    51597.    8.07KB     5.16  9999
# 3 rowSums2_noNames   18.3us   19.8us    50170.    8.07KB    10.0   9998

# 0.60.1
#   expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
#   <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
# 1 rowSums            47.6us   48.1us    20472.    7.86KB     4.10  9985
# 2 rowSums2           39.9us   40.2us    24652.    7.86KB     2.47  9999
# 3 rowSums2_noNames     40us   40.2us    24597.    7.86KB     4.92  9998
```

**Comment by yaccos** [comment]
`matrixStats` 0.60.1 features a major revision of the low-level C source code, but the user interface is expected to be the same (see the [NEWS](https://github.com/HenrikBengtsson/matrixStats/blob/0158d9a34c5485cb4c7b55c164ee30a6b31bb9a2/NEWS#L17)). As restructuring the C-level code was my idea, I am surprised that the performance penalty is that great when no indicies are provided. As the new code includes `if`-statements inside the tightest loops, I would imagine that passing the compiler flag `-fmove-loop-invariants` could mitigate the situation. If not, we have to profile the code to see what is going on.

**Comment by yaccos** [comment]
I have experimented with different compiler optimization flags. The benchmarks are made with R version 4.1.0 running under macOS 11.5.1 with Apple clang version 12.0.5 (clang-1205.0.22.11).

```R
library(matrixStats)
library(bench)

nr <- 1000
nc <- 20

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
dim(x)

br <- mark(rowSums = rowSums(x),
           rowSums2 = rowSums2(x),
           rowSums2_noNames = rowSums2(x, useNames = F))
br[, 1:7]

# 0.60.0 -O0
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums              48µs   52.4µs    17936.    7.86KB     2.03  8817
2 rowSums2            198µs  203.7µs     4584.   22.49KB     0     2292
3 rowSums2_noNames    199µs  202.9µs     4644.    8.07KB     0     2322


# 0.60.1. -O0
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.7µs   51.7µs    18406.    7.86KB     2.04  9034
2 rowSums2          237.6µs  244.8µs     3772.   11.71KB     0     1886
3 rowSums2_noNames  237.7µs  240.2µs     3946.    7.86KB     0     1973

# 0.60.0 -O1
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.2µs   53.4µs    17596.    7.86KB     2.02  8705
2 rowSums2           20.4µs   21.9µs    40288.   22.49KB     4.03  9999
3 rowSums2_noNames   20.9µs   22.1µs    41141.    8.07KB     4.11  9999

# 0.60.1 -O1
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.8µs   53.7µs    17002.    7.86KB     2.02  8413
2 rowSums2           39.2µs   41.2µs    22455.   11.71KB     2.25  9999
3 rowSums2_noNames     39µs   41.2µs    22929.    7.86KB     2.29  9999

# 0.60.0 -O2
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.7µs   53.1µs    17632.    7.86KB     2.02  8723
2 rowSums2           20.9µs   21.9µs    42445.   22.49KB     4.24  9999
3 rowSums2_noNames   21.4µs   22.4µs    41799.    8.07KB     4.18  9999

# 0.60.1 -O2

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.3µs   54.5µs    16670.    7.86KB     2.02  8252
2 rowSums2             45µs   48.1µs    19674.   11.71KB     2.03  9698
3 rowSums2_noNames     45µs   47.8µs    20002.    7.86KB     2.03  9874

# 0.60.0 -O3

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.7µs   54.1µs    16736.    7.86KB     2.02  8270
2 rowSums2           16.5µs   18.1µs    48735.   22.49KB     4.87  9999
3 rowSums2_noNames   17.2µs   18.1µs    51498.    8.07KB     5.15  9999

# 0.60.1 -O3

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            49.1µs   55.6µs    16790.    7.86KB     2.02  8300
2 rowSums2           25.7µs   26.9µs    33502.   11.71KB     3.35  9999
3 rowSums2_noNames   25.7µs   26.9µs    34302.    7.86KB     3.43  9999

# 0.60.0 -Ofast

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.7µs   54.1µs    16822.    7.86KB     2.02  8322
2 rowSums2           16.9µs     18µs    49396.   22.49KB     4.94  9999
3 rowSums2_noNames   17.4µs   18.4µs    50945.    8.07KB     5.10  9999

# 0.60.1 -Ofast

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            48.7µs   50.7µs    18524.    7.86KB     2.03  9136
2 rowSums2             41µs   46.4µs    19880.    7.86KB     2.03  9802
3 rowSums2_noNames   40.5µs   45.3µs    20981.    7.86KB     4.20  9998
```

**Comment by yaccos** [comment]
However, the performance degradation is absent when applied to larger matrices (`nr = 100000` and `nc = 2000`:

# 0.60.0 -O3

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums          425.77ms 429.84ms     2.33      781KB        0     2
2 rowSums2            2.08s    2.08s     0.480     811KB        0     1
3 rowSums2_noNames    2.11s    2.11s     0.474     797KB        0     1

# 0.60.1 -O3

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums          425.22ms 440.74ms     2.27      805KB        0     2
2 rowSums2            2.02s    2.02s     0.495     785KB        0     1
3 rowSums2_noNames    2.01s    2.01s     0.498     781KB        0     1

**Comment by yaccos** [comment]
I wondered what would happen if I took a large matrix and computed colsums instead of rowsums:

```R
library(devtools)
library(matrixStats)
library(bench)

nr <- 100000
nc <- 2000

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
dim(x)
x <- t(x)
br <- mark(colSums = colSums(x),
           colSums2 = colSums2(x),
           colSums2_noNames = colSums2(x, useNames = F))
br[, 1:7]

# 0.60.0 and -O3

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 colSums             157ms    158ms      6.31     781KB        0     4
2 colSums2            156ms    156ms      6.39     797KB        0     4
3 colSums2_noNames    155ms    158ms      6.36     797KB        0     4

# 0.60.1 and -O3

  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 colSums             148ms    156ms      6.47     781KB        0     4
2 colSums2            170ms    187ms      5.50     785KB        0     3
3 colSums2_noNames    168ms    172ms      5.79     781KB        0     3
```

When comparing this to the benchmark for rowsums, it seems like the `matrixStats::rowSums2` suffers from memory latency when the matrix cannot fit into the cache.

**Comment by yaccos** [comment]
As said, we should profile the code to eliminate the bottleneck. Look here for suggested tools: https://twitter.com/jakob_peder/status/1437742577952903168?s=20

**Comment by yaccos** [comment]
I have recently done a benchmark with R version 4.1.0 running under Ubuntu with gcc 9.3.0 and optimization flag `-O3`:

```
library(matrixStats)
library(bench)

nr <- 1000
nc <- 20

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
dim(x)

br <- mark(rowSums = rowSums(x),
           rowSums2 = rowSums2(x),
           rowSums2_noNames = rowSums2(x, useNames = F))
br[, 1:7]

# 0.60.0
#  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
#  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
# 1 rowSums            36.4µs   42.8µs    22889.    7.86KB     2.29  9999
# 2 rowSums2             15µs   18.1µs    51522.   22.49KB     5.15  9999
# 3 rowSums2_noNames     17µs   18.7µs    51065.    8.07KB     5.11  9999
```

**Comment by HenrikBengtsson** [comment]
Instead of testing `(rows == NULL)` and `(colOffset == NULL)` in each iteration, using "boolean" `norows` and `nocols` for these seems to improve things, cf. https://github.com/HenrikBengtsson/matrixStats/commit/3f82ff4f9c418f58e9464e9742e0b3de6eed93ee.

```
matrixStats 0.60.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.1µs   46.7µs    20538.   31.79KB     8.22  9996
2 rowSums2           19.3µs   22.2µs    44947.   22.49KB     8.99  9998
3 rowSums2_noNames   19.6µs   20.2µs    48701.    8.07KB     4.87  9999
```

```r
matrixStats 0.60.1
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.2µs   46.8µs    20794.   31.79KB     8.32  9996
2 rowSums2             38µs   40.5µs    24512.   11.71KB     2.45  9999
3 rowSums2_noNames     38µs   38.3µs    24912.    7.86KB     4.98  9998
```

```
matrixStats 0.61.0.9000
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums              46µs   46.7µs    21019.   31.79KB     8.41  9996
2 rowSums2             29µs   31.7µs    31380.   11.72KB     3.14  9999
3 rowSums2_noNames   29.1µs   29.4µs    32399.    7.86KB     6.48  9998
```

**Comment by HenrikBengtsson** [comment]
> It seems like the performance of matrixStats::rowSums2() is increased from version 0.60.1 to 0.61.0, but I cannot find any relevant changes in the C sources causing the performance gain. @HenrikBengtsson , what have you done?

This sounds like a false positive - there were no changes related to this code. Are you sure you used -O3 for 0.60.1?

**Comment by yaccos** [comment]
> This sounds like a false positive - there were no changes related to this code. Are you sure you used -O3 for 0.60.1?

Indeed I thought this was a false positive and therefore double-checked the results. And yes, the build configuration was exactly the same for all three versions, yet I got the same results listed above. Something really strange seems to be going on...

**Comment by yaccos** [comment]
Regarding "boolean" `norows` and `nocols`, I actually get retarded performance with my current setup (`-O3`)

Before:

```R
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            35.6µs   38.6µs    24582.    7.86KB     2.46  9999
2 rowSums2           20.7µs   22.5µs    38869.    7.86KB     3.89  9999
3 rowSums2_noNames   20.8µs   23.3µs    38303.    7.86KB     3.83  9999
```

After:

```R
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            35.4µs   37.9µs    25227.   10.23KB     7.57  9997
2 rowSums2           33.2µs   34.9µs    25326.    7.86KB     2.53  9999
3 rowSums2_noNames   33.2µs   34.8µs    26633.    7.86KB     2.66  9999
```

**Comment by yaccos** [comment]
For `-O2` however, I get a small performance boost for the same modification.

**Comment by HenrikBengtsson** [comment]
I've incorporated @yaccos PR #216 into the develop branch.  I'm confident that he has identified the culprit of the performance loss introduced matrixStats 0.60.1.  We are now back on track when it comes to performance for `rowSums2()`:

```
matrixStats 0.60.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.3µs   49.4µs    19837.   31.79KB     6.10  9752
2 rowSums2           19.6µs   23.3µs    42512.   22.49KB     8.50  9998
3 rowSums2_noNames   20.5µs   22.8µs    42232.    8.07KB     8.45  9998

matrixStats 0.60.1
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.4µs   49.4µs    19729.   31.79KB     6.11  9694
2 rowSums2           38.3µs     44µs    22444.   11.71KB     4.49  9998
3 rowSums2_noNames   38.1µs     44µs    22726.    7.86KB     2.27  9999

matrixStats 0.61.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.3µs   49.5µs    19674.   31.79KB     6.10  9668
2 rowSums2           38.1µs     44µs    22791.   11.71KB     4.56  9998
3 rowSums2_noNames     38µs     44µs    22766.    7.86KB     2.28  9999

matrixStats 0.61.0.9000
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums              46µs   50.3µs    18661.   31.79KB     8.18  9120
2 rowSums2             38µs   42.4µs    23565.   11.72KB     2.36  9999
3 rowSums2_noNames     38µs   43.5µs    22602.    7.86KB     2.26  9999

matrixStats 0.61.0.9001
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.1µs   47.2µs    20527.   31.79KB     6.16  9997
2 rowSums2             22µs   24.4µs    41604.   11.72KB     8.32  9998
3 rowSums2_noNames   22.1µs   24.9µs    40638.    7.86KB     4.06  9999
```

Now, we "just" have to apply the same fix for all other functions that were affected.

**Comment by yaccos** [comment]
After pull request #217 has been merged, I have provided another benchmark under R version 4.1.3 running under Ubuntu with gcc 9.3.0 and optimization flag `-O3`:

```R
library(matrixStats)
library(bench)

nr <- 1000
nc <- 20

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
dim(x)

br <- mark(rowSums = rowSums(x),
           rowSums2 = rowSums2(x),
           rowSums2_noNames = rowSums2(x, useNames = F))
br[, 1:7]

# 0.60.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            35.5µs   38.9µs    24376.    7.86KB     2.44  9999
2 rowSums2           15.1µs     17µs    53412.   22.49KB    10.7   9998
3 rowSums2_noNames   15.6µs   17.7µs    50181.    8.07KB     5.02  9999

# 0.60.1
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            35.5µs     38µs    25203.   31.79KB     2.52  9999
2 rowSums2           32.1µs   33.5µs    27412.   11.71KB     2.74  9999
3 rowSums2_noNames   32.3µs   32.8µs    29192.    7.86KB     2.92  9999

# 0.61.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            35.6µs   38.4µs    24887.    7.86KB     2.49  9999
2 rowSums2           20.1µs   21.2µs    42704.   11.72KB     4.27  9999
3 rowSums2_noNames   20.1µs   21.3µs    43206.    7.86KB     4.32  9999

According to what I can see, the performance problems are mostly solved.

**Comment by yaccos** [comment]
Also, I have been exited to measure performance on subsetted computations (same setup)

```R
library(matrixStats)
library(bench)

nr <- 1000L
nr_subset <- 500L
nc <- 20L

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
row_subset <- sample(1:nr,size = nr_subset)
dim(x)

br <- mark(rowSums = rowSums(x[row_subset,]),
           rowSums2 = rowSums2(x, rows = row_subset),
           rowSums2_noNames = rowSums2(x, rows = row_subset,useNames = FALSE))
br[, 1:7]

# 0.60.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            34.8µs   51.2µs    17619.   82.12KB    27.6   7648
2 rowSums2           11.8µs   13.5µs    66521.   18.59KB     6.65  9999
3 rowSums2_noNames     12µs     14µs    64275.    4.16KB     6.43  9999

# 0.60.1
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            34.7µs   35.5µs    25931.   82.12KB    36.4   9986
2 rowSums2             18µs   18.8µs    48679.   11.77KB     9.74  9998
3 rowSums2_noNames     18µs     19µs    47129.    7.91KB     4.71  9999


# 0.61.0
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            34.7µs   50.5µs    19136.   82.12KB     32.9  8144
2 rowSums2           12.4µs   13.1µs    72598.    7.91KB     14.5  9998
3 rowSums2_noNames   12.4µs   12.7µs    74429.    7.91KB     14.9  9998
```
Also this performance degradation has essentially vanished.

**Comment by yaccos** [comment]
> Thanks. Just to make sure, is the latter for 0.61.0-9003?

Yes, the latter performance metrics are for 0.61.0-9003 currently on the `develop` branch.

**Comment by minemR** [comment]
Testing 3 versions on Windows, we can see that there's some performance degradation from 9001 to 9003
```
# ‘0.61.0’ CRAN
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.8us   49.3us    19785.   31.77KB     4.15  9538
2 rowSums2           39.6us     41us    24124.   11.71KB     7.24  9997
3 rowSums2_noNames   39.7us   41.3us    23592.    7.86KB     2.36  9999

# ‘0.61.0.9001’
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.7us   47.3us    20793.    7.86KB     2.08  9999
2 rowSums2           20.6us   21.9us    44001.    7.86KB     8.80  9998
3 rowSums2_noNames   20.6us     21us    45798.    7.86KB     9.16  9998

# ‘0.61.0.9003’
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            46.7us   49.7us    20027.   31.77KB     4.16  9632
2 rowSums2           30.5us   31.8us    30927.   11.73KB     6.19  9998
3 rowSums2_noNames   30.5us   30.8us    31170.    7.86KB     9.35  9997
```

**Comment by yaccos** [comment]
@minemR, there are a few points which are relevant in this respect:

1. The optimization present in 0.61.0.9001 **only** applies to `rowSums2()` and `colSums2()`. For the other functions in the API, the mentioned performance degradation is not mitigated in 0.61.9.9001. As discussed in #216, introducing the same change to all functions in `matrixStats` would to inconvenient to implement (introduces a layer of if-else-blocks within existing for-loops) and lead to untidy code which is hard to maintain. Therefore, for #217, I chose an approach which requires less confusing changes in the codebase. This is centered around passing the flags `rowsHasNA` and  `colsHasNA` to the macros which checks for NA values.
2. In theory, `rowSums2()` in 0.61.0.9003 should be almost as performant as in 0.61.0.9001, but requires more sophisticated compiler optimizations to work efficiently. What compiler flags did you use for your benchmark?

**Comment by HenrikBengtsson** [comment]
>     2. In theory, `rowSums2()` in 0.61.0.9003 should be almost as performant as in 0.61.0.9001, but requires more sophisticated compiler optimizations to work efficiently. What compiler flags did you use for your benchmark?

Sorry folks, I haven't had time to look into this, but this thought struck late some night. @yaccos, in your [comment above](https://github.com/HenrikBengtsson/matrixStats/issues/212#issuecomment-1091622131) you do mention you compile with `-O3`.  I think, it's very important that we benchmark with the defaults, which is what the 99.99999% of all users will use, e.g. on my Linux system and RStudio Cloud, I see:

```sh
$ R CMD config CFLAGS
-g -O2
```

If `-O3` is required to get better performance, we need to have a discussion on how to deploy that for all users.  Regardlessly,, we should benchmark all versions of **matrixStats** using the same optimization flags, may it be `-O2` or `-O3`, so we compare apples to apples everywhere.

**Comment by yaccos** [comment]
In conclusion, the best performance for 0.61.0.9003 is achieved with `-O3` and provides a decently narrow gap to 0.61.0.9001 compared to the situation with `-O2`. We could probably add `-O3` to `src/Makevars` to ensure the users will get this optimization level. Turning on native optimizations (banned by CRAN for good reasons) however, does not seem to help performance.

**Comment by yaccos** [comment]
Citing [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars):
> Also, do not set variables such as CPPFLAGS, CFLAGS etc.: these should be settable by users (sites) through appropriate personal (site-wide) Makevars files.

As I read this, it means that package developers should not try to override package compilation optimization levels and hence hard-coding the optimization level in the package would be viewed as anti-social.

**Comment by HenrikBengtsson** [comment]
Coincidentally, a warning about `-O3` was just added to core R (https://github.com/wch/r-source/commit/889855532dbbdd403d94564b8b364d9cacbc356a) some hours ago:

> Do not use @option{-O3} with @command{gcc} 11.0 or 11.1: it mis-compiles
code including in package @CRANpkg{MASS} resulting in plausible but
incorrect results.

**Comment by yaccos** [comment]
> Coincidentally, a warning about `-O3` was just added to core R ([wch/r-source@8898555](https://github.com/wch/r-source/commit/889855532dbbdd403d94564b8b364d9cacbc356a)) some hours ago:
> 
> > Do not use @option{-O3} with @command{gcc} 11.0 or 11.1: it mis-compiles
> > code including in package @CRANpkg{MASS} resulting in plausible but
> > incorrect results.

According to the same manual, running `-O3` may cause problems for certain other CRAN packages. This is either due to compiler bugs (unlikely) or undefined behaviour in the package sources (the most likely explanation). At least this explains why `-O2` is the default optimization level instead of `-O3`.

**Comment by yaccos** [comment]
Anyway, this is quite a bit of a headache for me. I have tried various approaches, the [most performant one](https://github.com/yaccos/matrixStats/commit/e3b1ec97ec57fbbfe212ba44390893790ad649de) yielded with the same setup as before and `-O2`:

```R
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            47.9µs   53.3µs    17800.    7.86KB     2.05  8663
2 rowSums2           29.8µs   32.9µs    28438.    7.86KB     2.84  9999
3 rowSums2_noNames     30µs   31.3µs    29662.    7.86KB     2.97  9999
```

However, this approach uses statement expressions which is a non-standard compiler feature, which means that even though it should work for modern mainstream compilers, it may fail for machines using unusual or outdated compilers. I could theoretically make a more performant solution with some macro trickery to branch on NA checks before the loops. However, this would require considerable amounts of work and effort, in addition to provide less readable code,  so I do not consider it worth the effort.

The performance of version 0.61.0.9003 is still better than for the current version 0.61.0 on CRAN even with `-O2`, so I would suggest we consider the current performance good enough.

**Comment by HenrikBengtsson** [comment]
With the most recent develop version (**matrixStats** 0.63.0.9005), we're back in business;

```r
library(matrixStats)
library(bench)

nr <- 1000
nc <- 20

set.seed(1)
x <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
dim(x)

br <- mark(rowSums = rowSums(x),
           rowSums2 = rowSums2(x),
           rowSums2_noNames = rowSums2(x, useNames = F))
[1] 1000   20
> br[,1:7]
# A tibble: 3 × 7
  expression            min   median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int>
1 rowSums            41.3µs   45.5µs    21892.   31.79KB     8.76  9996
2 rowSums2           15.2µs   18.2µs    53708.    13.3KB    10.7   9998
3 rowSums2_noNames   15.3µs   17.6µs    54762.    7.86KB     5.48  9999
```

This is thanks to work by @yaccos, cf. PR #229.
