### ISSUE TITLE
Packages that break with new useNames=TRUE

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#227]
With the new `useNames = TRUE` as the default, there is 1 broken Bioconductor release package and 6 broken Bioconductor devel packages (2023-07-16).  All CRAN packages are ok.

# CRAN

  * [x] [Canek](https://cran.r-project.org/package=Canek) 0.2.1 (2022-05-10), 0.2.2 (2023-05-31)
     - [x] Issue/PR: https://github.com/MartinLoza/Canek/issues/12 (2023-03-21)
     - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#canek 

_Last updated: 2023-06-01_

# Bioconductor

  * [ ] [MatrixGenerics](https://bioconductor.org/packages/devel/bioc/html/MatrixGenerics.html)
    - Issues: https://github.com/Bioconductor/MatrixGenerics/issues/31
    - [x] Fixed in Bioc release (MatrixGenerics 1.12.1; 2023-06-10)
    - [ ] Fixed in Bioc devel
    
  * [ ] [sparseMatrixStats](https://bioconductor.org/packages/devel/bioc/html/sparseMatrixStats.html)
    - Notes: Already prepared for the move, cf. <https://github.com/const-ae/sparseMatrixStats/tree/change_useNames_default>
    - Remaining issues: https://github.com/const-ae/sparseMatrixStats/issues/26
    - [x] Fixed in Bioc release
    - [ ] Fixed in Bioc devel

  * [ ] [DelayedMatrixStats](https://bioconductor.org/packages/devel/bioc/html/DelayedMatrixStats.html)
    - Issue: https://github.com/PeteHaitch/DelayedMatrixStats/issues/91
    - [x] Fixed in Bioc release
    - [ ] Fixed in Bioc devel

  * [x] [BASiCS](https://bioconductor.org/packages/release/bioc/html/BASiCS.html)
    - [x] Fixed in Bioc release
    - [x] Fixed in Bioc devel
    - GitHub: https://github.com/catavallejos/BASiCS
    - Notes: Imports only from **matrixStats**
    - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#basics

  * [ ] [CATALYST](https://bioconductor.org/packages/devel/bioc/html/CATALYST.html)
    - [x] Fixed in Bioc release (Check error is gone without package being updated; looks like there was an indirect dependency on MatrixStats, which has been updated since. /2023-06-14)
    - [ ] Fixed in Bioc devel
    - GitHub: https://github.com/HelenaLC/CATALYST
    - Notes: Imports only from **matrixStats**
    - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#catalyst

  * [ ] [glmGamPoi](https://bioconductor.org/packages/devel/bioc/html/glmGamPoi.html)
    - [x] Fixed in Bioc release
    - [ ] Fixed in Bioc devel
    - GitHub: https://github.com/const-ae/glmGamPoi
    - Notes: It uses functions from both **matrixStats** and **DelayedMatrixStats**
    - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#glmgampoi
     
  * [ ] [metagenomeSeq](https://bioconductor.org/packages/release/bioc/html/metagenomeSeq.html)
    - [ ] Fixed in Bioc release
    - [ ] Fixed in Bioc devel
    - GitHub: https://github.com/HCBravoLab/metagenomeSeq
    - Notes: Imports only from **matrixStats**
    - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#metagenomeseq
    
  * [x] [scp](https://bioconductor.org/packages/release/bioc/html/scp.html)
    - [x] Fixed in Bioc release
    - [x] Fixed in Bioc devel
    - GitHub: https://github.com/UCLouvain-CBIO/scp
    - Notes: Imports only from **matrixStats**
    - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#scp
    
  * [x] [scPCA](https://bioconductor.org/packages/devel/bioc/html/scPCA.html)
    - [x] Fixed in Bioc release (Check error is gone without package being updated; looks like there was an indirect dependency on MatrixStats, which has been updated since. /2023-06-14)
    - [x] Fixed in Bioc devel
    - GitHub: https://github.com/PhilBoileau/scPCA
    - Notes: It uses functions from both **matrixStats** and **DelayedMatrixStats**
    - Error: https://github.com/HenrikBengtsson/matrixStats/blob/58a8b54f571cb4fbae65b1bc4d738e2a2dd8e8b1/revdep/problems.md#scpca
     
_Last updated: 2023-07-16_

Regardless what the new default will be, these should be updated to explicitly set `useNames = FALSE` in the locations where `useNames = TRUE` break.

**Comment by yaccos** [comment]
For at least some of the packages, the regression is related to the fact that the test code observes that one vector is named, whereas the other is not and thus reports a failure.

**Comment by HenrikBengtsson** [comment]
Can someone help reaching out to the above 6 Bioconductor packages?

They need to update the parts of the code/tests that break if `useNames = TRUE` becomes the new default.  Note that the default might become FALSE, so they need to be updates to handle either case. The easiest is for them to specify `useNames = FALSE` where the code/tests break, because that seems to be what they expect the case to be right now.

**Comment by const-ae** [comment]
Hi Henrik, 

I have been following this issue, I just have been very busy the past two weeks and an ok holidays until the end of next week. But I plan to update sparseMatrixStats when I am back :)

**Comment by HenrikBengtsson** [comment]
Several Bioconductor packages on the Bioc devel branch are still broken. But since it's been 1.5 months since matrixStats 1.0.0 was released, I'll stop monitoring these broken packages.

**Comment by PeteHaitch** [comment]
We've got a patches for **MatrixGenerics** and **DelayedMatrixStats** (and I think **sparseMatrixStats**) ready for BioC-devel.
I'm waiting to hear back from Herve (who I think is on leave) and then we'll incorporate.

**Comment by HenrikBengtsson** [comment]
That's good news. Thanks for the update.

**Comment by PeteHaitch** [comment]
I've just pushed the patched versions of **MatrixGenerics** and **DelayedMatrixStats** to Bioconductor's git server.
I think @const-ae has already pushed his updates to **sparseMatrixStats** - is that right @const-ae ?

I'll keep an eye on the next build report but these build locally for me.

**Comment by const-ae** [comment]
> I think @const-ae has already pushed his updates to sparseMatrixStats - is that right @const-ae ?

Yes :)

**Comment by HenrikBengtsson** [comment]
> > I think @const-ae has already pushed his updates to sparseMatrixStats - is that right @const-ae ?
> 
> Yes :)

@const-ae , it looks like the Bioc devel version still needs to be fixed.
