### ISSUE TITLE
Default 'useNames' argument - take 2

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#232]
Alright, I've listened, and I thought about it, and then I thought about it even more.  I think it's okay to make:

* `useNames = TRUE`

the new default.

Advantages:

* Name attributes are processed by default, which makes life easier for most people (less typing)
* It is consistent with `colMeans()`, `rowMeans()`, `colSums()`, `rowSums()`, and `apply()`

Disadvantages:

* It adds performance and memory overhead
* Not everyone will know about `useNames = FALSE` (compared to everyone would know about `useNames = TRUE` if they need names)
* It introduces a new overhead to existing packages (n=443; 2023-05-24)
* Package maintainers who suffer from the new overhead might not notice for a long time, so it might be a while before they add `useNames = FALSE`

But, as others tried to convince me in the past, the advantages outweight the disadvantages.

So, the new plan is to go with `useNames = TRUE`.

FWIW, there are currently a few packages that will break when we make `useNames = TRUE` the default, cf. Issue #227.  They have been informed several times already.

**Comment by HenrikBengtsson** [comment]
Thanks for spotting this. Can you please repost this as a separate issue?

**Comment by HenrikBengtsson** [comment]
UPDATE: I'm doing the last validations before submitting this new version to CRAN.

**Comment by HenrikBengtsson** [comment]
matrixStats 1.0.0 is now on CRAN.

**Comment by const-ae** [comment]
Congrats :)
