### ISSUE TITLE
useNames documentation has wrong default

### ISSUE THREAD

**Issue by PeteHaitch** [HenrikBengtsson/matrixStats#240]
Hi Henrik,

The `Arguments` section of the documentation has the default value of `useNames` being `FALSE` but it is really `TRUE`.
E.g., https://github.com/HenrikBengtsson/matrixStats/blob/512292964d28f88cddac590f9ae2820987bd93fd/man/rowSums2.Rd#L35-L37

Cheers,
Pete

**Comment by HenrikBengtsson** [comment]
Thanks. Fixed, cf. commit https://github.com/HenrikBengtsson/matrixStats/commit/e173995f086eaf73c8c8c204bd6f043203bf1492
