### ISSUE TITLE
Make a scalar `center` argument for matrix functions defunct

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#254]
We have had the following since matrixStats 0.58.0 (2021-01-26):

 * Using a scalar value for argument `center` of `colSds()`,
   `rowSds()`, `colVars()`, `rowVars()`, `colMads()`, `rowMads()`,
   `colWeightedMads()`, and `rowWeightedMads()` is now deprecated.

We should move to make it defunct by default.
 
I've started revdep checks with `R_MATRIXSTATS_CENTER_ONSCALAR=defunct` to see if there are any negative side effects.

**Comment by HenrikBengtsson** [comment]
@PeteHaitch, passing a scalar to argument `center` will soon be defunct.  I noticed that you explicitly allow for scalars in https://github.com/PeteHaitch/DelayedMatrixStats/blob/20c2e278d9ccf503a49dd489dc3597a21443c01d/R/rowVars.R#L16-L25.

**Comment by HenrikBengtsson** [comment]
@const-ae, FYI, passing a scalar to argument `center` will soon be defunct; currently deprecated.  I noticed that **sparseMatrixStats** accepts scalar `center` values, e.g.

```r
> sparseMatrixStats::colVars(sparse_mat, center = 4)
[1] 17.7777778  0.0000000  0.4444444  1.8888889  1.0000000  0.0000000
```

**Comment by PeteHaitch** [comment]
Thanks for the heads up. I'll take care of it before the upcoming BioC release.

**Comment by HenrikBengtsson** [comment]
Thank you. I've checked that there are no negative revdep side effects, so this will now be the default in the next release.

**Comment by PeteHaitch** [comment]
Is the new release imminent?
More exactly, is it likely to be before or after the upcoming BioC release?

**Comment by HenrikBengtsson** [comment]
I'm thinking before ... Would it matter, given that I don't find any revdep packages being affected?

**Comment by HenrikBengtsson** [comment]
... and in worst case scenario (for current Bioc release and likes), it can for now be reverted using:

```
R_MATRIXSTATS_CENTER_ONSCALAR=deprecated
```

or in R, by:

```r
options(matrixStats.center.onScalar = "deprecated")
```

**Comment by PeteHaitch** [comment]
Thanks for the extra info.
I don't expect it to matter but it's helpful to me in prioritising tasks as the BioC release approaches.

**Comment by PeteHaitch** [comment]
Made the change for [current devel (BioC 3.19)](https://github.com/PeteHaitch/DelayedMatrixStats/commit/9048f3e7a24035f3526a2ac0455598138e0c8480) but not touched current release (BioC 3.18).
