### ISSUE TITLE
BUG (in R): cummax(c(NA_integer_, x)) gives c(NA_integer_, cummax(x))

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#30]
Although this is not a bug in matrixStats per se, it's related `rowCummaxs()` and the tests of it, so I'm adding it as an issue here:

@Dongcan-Jiang reported:

> The function cummax() seems to have a bug.
>
>> x <- c(NA, 0)
>> storage.mode(x) <- "integer"
>> cummax(x)
> [1] NA  0
>
> The correct result of this case should be NA NA. The mistake in
> [https://github.com/wch/r-source/blob/trunk/src/main/cum.c#L130-L136] may be
> the reason.

**Comment by HenrikBengtsson** [comment]
From code inspection this bug happens for only:
* for `integer` values
* when the _first_ element is `NA_integer_`

Examples:
```r
# Numeric/doubles works as expected
> cummax(c(NA_real_, 0, 1, 2, 3))
[1] NA NA NA NA NA

# It does not occur when the first value is non-NA
> cummax(c(0L, NA_integer_, 1L, 2L, 3L))
[1]  0 NA NA NA NA

# When first value is NA, it is not "remembered"
# (because internal for loop starts with 2nd element)
> cummax(c(NA_integer_, 0L, 1L, 2L, 3L))
[1] NA  0  1  2  3
```

The problem is _not_ there for `cummin()`:
```r
> cummin(c(0L, NA_integer_, 1L, 2L, 3L))
[1]  0 NA NA NA NA
> cummin(c(NA_integer_, 0L, 1L, 2L, 3L))
[1] NA NA NA NA NA
```
but that is probably just "pure luck" due to the fact how `NA_integer_` is represented internally.  The code makes the same mistake where the for-loop skips the test for NA of the first element, cf. https://github.com/wch/r-source/blob/trunk/src/main/cum.c#L145-L148

**Comment by HenrikBengtsson** [comment]
@Dongcan-Jiang, would you mind posting these findings to R-devel (you need to be subscribed to the list)?  I'm sure R core will appreciate it.  To make it easier for them, you could even suggest a patch, which they prefer in the output of `svn diff src/main/cum.c`, which means you need to `svn checkout https://svn.r-project.org/R/trunk/` (they're not working with git).

**Comment by HenrikBengtsson** [comment]
@Dongcan-Jiang, I see [you've already posted to R-devel](https://stat.ethz.ch/pipermail/r-devel/2015-May/071190.html).  Thanks for doing that.

**Comment by mmaechler** [comment]
I have fixed it in R now.

**Comment by HenrikBengtsson** [comment]
Thanks @mmaechler.  I forgot that you're a follower here :)

BTW, are you sure you don't want to do [the same](https://github.com/wch/r-source/commit/83a7d309308feace0507731d150cfb735574d062) for [`icummin()`](https://github.com/wch/r-source/blob/trunk/src/main/cum.c#L145-L148), because that code is really relying on `NA_INTEGER < ix[i]`.  It also does _not_ do early stopping if the first element is NA and the following are finite integers; then it has to run through the complete vector.

**Comment by mmaechler** [comment]
Yes, I consciously made the decision... had the code already there when I noticed it was not necessary.  I *did* add regression test for the case.
The  integer - (NA, <non-NA>, ...)  case *is* pretty rare  *and* the algorithm *is*   O(n) in all cases.

**Comment by HenrikBengtsson** [comment]
Got it.
