### ISSUE TITLE
The function x_OP_y() seems to have a bug.

### ISSUE THREAD

**Issue by Dongcan-Jiang** [HenrikBengtsson/matrixStats#34]
//Example
```
> x <- matrix(NA_integer_, nrow=2, ncol=2)
> y <- 1L
> x_OP_y(x, y, "+")
            [,1]        [,2]
[1,] -2147483647 -2147483647
[2,] -2147483647 -2147483647
```

**Comment by HenrikBengtsson** [comment]
Added tests for this; this seems to happen when:
* `na.rm=FALSE`,
* both `x` and `y` are integers,
* one or both of them are `NA_integer_`, and
* for `OP`:s `"+"`, `"-"`, and `"*"` (for `OP="/"` there's another related issue)

Working on a fix.

**Comment by HenrikBengtsson** [comment]
Solved, cf. commit 9defd5d.  Added package tests.

**Comment by Dongcan-Jiang** [comment]
Does the following cases behave as what they intend?
```
> x <- matrix(NA_integer_, 1, 1)
> y <- NA_integer_
> x_OP_y(x,y,'-',na.rm=TRUE)
    [,1]
[1,]    0
> x_OP_y(x,y,'/',na.rm=TRUE)
    [,1]
[1,]    1
> x_OP_y(x,-1L,'-',na.rm=TRUE)
           [,1]
[1,] -2147483647
```

**Comment by HenrikBengtsson** [comment]
I added tests that covered this case too and then incorporated your PR #37.  Thanks.
