### ISSUE TITLE
Something confusing in inst/benchmarking/anyMissing.md.rsp

### ISSUE THREAD

**Issue by Dongcan-Jiang** [HenrikBengtsson/matrixStats#44]
When I'm working on subsetting benchmark reports, I find something confusing.

## 1. [Line 55 in anyMissing.md.rsp](https://github.com/HenrikBengtsson/matrixStats/blob/develop/inst/benchmarking/anyMissing.md.rsp#L55)
It looks that `x <- data[[.dataLabel.]]` is unnecessary, as `x` has already been assigned on [Line 48](https://github.com/HenrikBengtsson/matrixStats/blob/develop/inst/benchmarking/anyMissing.md.rsp#L48).

## 2. [Line 49 in anyMissing.md.rsp](https://github.com/HenrikBengtsson/matrixStats/blob/develop/inst/benchmarking/anyMissing.md.rsp#L49)
`gc()` on [this line](https://github.com/HenrikBengtsson/matrixStats/blob/develop/inst/benchmarking/anyMissing.md.rsp#L49) seems to be redundant, because it will be called on [Line 56](https://github.com/HenrikBengtsson/matrixStats/blob/develop/inst/benchmarking/anyMissing.md.rsp#L56).

**Comment by HenrikBengtsson** [comment]
Most likely leftovers from cut'n'pasting between report templates.  I've cleanup it up in commit 741a242.  Thxs.
