### ISSUE TITLE
clang compile warning: comparison of constant -4503599627370497 with expression of type 'int' is always false

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#68]
# Issue
Checking branches `feature/subsetting` and `feature/multicore` with `clang-3.6 -fsanitize=undefined` (see Issue #50) gives several compile warnings on:
```c
clang-3.6 -fsanitize=undefined -fno-sanitize=float-divide-by-zero -I/usr/share/R
/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=f
ormat-security -D_FORTIFY_SOURCE=2 -g  -c logSumExp.c -o logSumExp.o
In file included from logSumExp.c:26:
In file included from ./templates-gen-vector.h:6:
./logSumExp_TYPE-template.h:55:11: warning: comparison of constant -450359962737
0497 with expression of type 'int' is always false [-Wtautological-constant-out-
of-range-compare]
    idx = R_INDEX_OP(IDX_INDEX(cidxs,0), *, by);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./templates-types.h:375:55: note: expanded from macro 'R_INDEX_OP'
  #define R_INDEX_OP(a, OP, b) (a == NA_R_XLEN_T || b == NA_R_XLEN_T ? NA_R_XLEN_T : a OP b)
                                                      ^  ~~~~~~~~~~~
```

BTW, the above error also appear if one compile manually as:
```c
$ clang-3.6 -fsanitize=undefined -I/usr/share/R/include -c src/logSumExp.c
```

# Troubleshooting
This is because of [how `NA_R_X_LEN_T` is defined](https://github.com/HenrikBengtsson/matrixStats/blob/feature/subsetting/src/types.h#L46-L51):
```c
/* define NA_R_XLEN_T */
#ifdef LONG_VECTOR_SUPPORT
  #define NA_R_XLEN_T -4503599627370497
#else
  #define NA_R_XLEN_T NA_INTEGER
#endif
```
and the `b` argument to `R_INDEX_OP(a, OP, b)` is an `int`.  BTW, in R `NA_INTEGER` equals `R_NaInt == INT_MIN == -2147483648`.

**Comment by HenrikBengtsson** [comment]
@Dongcan-Jiang, trying to troubleshoot this one; from where did you get the number `-4503599627370497`?

**Comment by HenrikBengtsson** [comment]
Clarification: This issue originates from two files / functions:

* src/logSumExp.c
* src/rowRanksWithTies.c

```sh
$ make clang-ubsan &> clang-ubsan.log
$ grep -F .c clang-ubsan.log | sort -u
clang -fsanitize=undefined -I/usr/share/R/include -c src/*.c
In file included from src/logSumExp.c:26:
In file included from src/rowRanksWithTies.c:26:
In file included from src/rowRanksWithTies.c:30:
In file included from src/rowRanksWithTies.c:36:
In file included from src/rowRanksWithTies.c:40:
In file included from src/rowRanksWithTies.c:52:
In file included from src/rowRanksWithTies.c:56:
In file included from src/rowRanksWithTies.c:62:
In file included from src/rowRanksWithTies.c:66:
In file included from src/rowRanksWithTies.c:78:
In file included from src/rowRanksWithTies.c:82:
In file included from src/rowRanksWithTies.c:88:
In file included from src/rowRanksWithTies.c:92:
```

**Comment by HenrikBengtsson** [comment]
Update: I've updated branched `feature/subsetting` and `feature/multicore` such that the clang warnings are gone.

**Comment by Dongcan-Jiang** [comment]
@HenrikBengtsson I'm very sorry for the mistake. Thanks a lot for fixing it.

**Comment by HenrikBengtsson** [comment]
@Dongcan-Jiang, absolutely no worries.  I wouldn't have caught this without clang/UBSAN and I see that the one for `rowRanksWithTies.c` was fixed in the `multicore` branch.

I'm still curious about the constant `-4503599627370497`, that is, if you found that used/documented in R itself, or you came up with it yourself, e.g. `x = (R_len_t)y` where `y is `NA_real`?

FYI, I posted 'Long vectors: Missing values and R_xlen_t?' to R-devel yesterday (https://stat.ethz.ch/pipermail/r-devel/2015-September/071780.html).

**Comment by Dongcan-Jiang** [comment]
@HenrikBengtsson The constant -4503599627370497 was defined by myself in order to do the NA indexing[https://github.com/Dongcan-Jiang/matrixStats/blob/feature/multicore/src/templates-types.h#L398-L399]. AFAIK, R hasn't defined NA for R_xlen_t.

**Comment by HenrikBengtsson** [comment]
Ok, I see; so `NA_R_XLEN_T` is just a place holder for a missing value similar to how `NA_INTEGER` work, and it's needed in some of the code.  In [Simon Urbanek's reply](https://stat.ethz.ch/pipermail/r-devel/2015-September/071784.html) to my R-devel question, he says that it shouldn't really be used this way, but then gives an example that allows the user to choose - "often it's simply 0, other times -1".

However, if using 0 or -`, I'd say we can equally well use something analogue to `NA_INTEGER`.  So, your choice of value make sense.  I decided on the following clarification:
```r
/* define NA_R_XLEN_T */
#ifdef LONG_VECTOR_SUPPORT
  #define R_XLEN_T_MIN R_XLEN_T_MAX-1
  #define NA_R_XLEN_T R_XLEN_T_MIN
#else
  #define NA_R_XLEN_T NA_INTEGER
#endif
```
which works because [src/include/Rinternals.h](https://github.com/wch/r-source/blob/223728213f390b8c1cd3a1e4b7ae68141d142800/src/include/Rinternals.h#L67-L76) defines:
```r
#ifdef LONG_VECTOR_SUPPORT
    typedef ptrdiff_t R_xlen_t;
    typedef struct { R_xlen_t lv_length, lv_truelength; } R_long_vec_hdr_t;
# define R_XLEN_T_MAX 4503599627370496
# define R_SHORT_LEN_MAX 2147483647
# define R_LONG_VEC_TOKEN -1
#else
    typedef int R_xlen_t;
# define R_XLEN_T_MAX R_LEN_T_MAX
#endif
```
BTW, `R_xlen_t` is `ptrdiff_t` which is _signed_ so choosing a negative value does work.
