### ISSUE TITLE
weightedVar

### ISSUE THREAD

**Issue by Radibor** [HenrikBengtsson/matrixStats#72]
Hello,

I believe the weightedVar function is incorrect because of the term (n / (n-1L)).  

Here's a fix:

DELETED w <- w / sum(w)

  if (is.null(center)) {
    center <- sum(w / sum(w) * x)
  }
  x <- x - center
  x <- x^2
  sigma2 <- sum(w * x) / (sum(w) - 1L)
  x <- w <- NULL
  sigma2

This version yields the same results as wtd.var from package Hmisc.

Regards
Wolfgang

**Comment by HenrikBengtsson** [comment]
Thanks for the report.

Looking at the current [tests/weightedVar_etal.R]( (https://github.com/HenrikBengtsson/matrixStats/blob/master/tests/weightedVar_etal.R), it's clear that we have _forgotten_ about testing `weightedVar()` et al. for correctness.  We(read _I_) have basically left out formal assertions (e.g. `stopifnot()`) for result being correct; all there is now is textual output.

So, the first thing that needs to be done is to add package tests that actually assert correctness for `weightedVar()`, `weightedSd()` and `weightedMad()`.  I'll get to this as soon as possible.

**Comment by HenrikBengtsson** [comment]
This seems to be valid, i.e. `weightedVar()` does not apply the proper correction factor.

Minor comment/observation: I think `weightedVar(x, w)` gives the same result as `Hmisc::wtd.var(x, w)` in the special case when `sum(w) == length(x)`, e.g.
```r
> large <- c(21, 8, 26, 1, 15, 33, 12, 25, 0, 84)
> years <- c(41706, 9301, 33678, 3082, 27040, 44188, 10049, 30591, 2275, 109831)
> Hmisc::wtd.var(large, years)
[1] 899.0098
> w <- years / sum(years) * length(years)
> Hmisc::wtd.var(large, w)
[1] 998.8966
> weightedVar(large, w)
[1] 998.8966
```
In all other cases, I tink it uses a correction factor that is a scalar which should be multiplied by:
```
tau <- (length(x) - 1) / length(x) / ((sum(w) - 1) / sum(w))
```
For example:
```r
> Hmisc::wtd.var(large, years)
[1] 899.0098
> w <- years / sum(years) * length(years)
> tau <- (length(years) - 1) / length(years) / ((sum(years) - 1) / sum(years))
> tau * weightedVar(large, w)
[1] 899.0098
```

**Comment by HenrikBengtsson** [comment]
@Radibor, I've fixed this and added redundancy tests. Please try it by installing the 'develop' branch (in a fresh R session):
```r
source('http://callr.org/install#HenrikBengtsson/matrixStats@develop')
```
Thanks again for reporting on this.  I'll try to submit to CRAN as soon as possible.

**Comment by HenrikBengtsson** [comment]
FYI, matrixStats 0.15.0 is now on CRAN and includes this fix. Thanks.
