### ISSUE TITLE
WISH: Add rowSums2() and rowMeans2() with subsetting support

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/matrixStats#82]
Now that we have subsetted support throughout the matrixStats package, maybe it makes sense to also provide versions of `base::rowSums()` and `base::rowMeans()` that also support subsetting arguments `rows` and `cols`.   To avoid name clash warnings everytime we attach matrixStats, we might want to use different names for these functions, e.g.
- `colSums2()` and `rowSums2()`
- `colMeans2()` and `rowMeans2()`.

Any other similar functions that should also be brought in?

Note that we already have `sumOver(x, idxs)` and  `meanOver(x, idxs)`.  If the above matrix functions are added, should the latter be renamed to `sum2()` and `mean2()`?

**Comment by HenrikBengtsson** [comment]
Notes to self:

* We have `sumOver(x, ..., mode = typeof(x))`.  The default mode emulates `sum(x)` such that if `sum(x)` integer overflows then `sumOver(x)` also does it.  However, using `sumOver(x, mode = "double")` will return the non-overflow sum as a numeric.  This is not possible with regular `sum()` where one needs to use `sum(as.double(x))` to achieve the same, which is a very expensive operation.

* Contrary to `sum()`, `rowSums()` and `colSums()` always return a numeric and never integer overflows.  If the result is long and one want integer results that approach may be inefficient, e.g. `rowSums(x)` for a tall-and-narrow integer matrix.

Thus, should `rowSums2()` and `colSums2()` take argument `mode = typeof(x)` analogously to `sumOver()`?  If so, then `rowSums2(x, mode = "integer")` may integer overflow for some of the rows.  Should the default be `mode = "double"` in order to emulate `rowSums()`?

**Comment by HenrikBengtsson** [comment]
Completed - the following will be part of the next release (currently in the `develop` branch):

* `colSums2()` and `rowSums2()`
* `sums2()` replaced now deprecated `sumOver()`
* `colMeans2()` and `rowMeans2()`
* `mean2()` replaced now deprecated `meanOver()`

**Comment by PeteHaitch** [comment]
It looks like you opted not to add a `mode` argument to `colSums2()` and `rowSums2()`. Is that correct? I was hoping to be able to return an integer vector for a row sums type operation on a long and skinny matrix with small integer entries, i.e. I'm basically certain the result won't overflow and returning an integer rather than numeric vector halves the storage requirements.

**Comment by HenrikBengtsson** [comment]
Cannot recall exactly why I skipped it; maybe I forgot or maybe I took a shortcut. Can you create a new issue for this feature request and add a small dummy example with example matrix, example call, and `str()` output your expect.
