### ISSUE TITLE
Travis fails when trying to install matrixStats

### ISSUE THREAD

**Issue by muschellij2** [HenrikBengtsson/matrixStats#88]
I have duplicated this on travis-ci repo:  https://github.com/travis-ci/travis-ci/issues/6267

I have found Travis fail when trying to installing matrixStats and says biocInstaller is needed.  I don't know if this happens because biocViews is in the `DESCRIPTION` (I doubt it though). 

To reproduce the error, I created a simple test package (with RStudio/devtools) and only depended on matrixStats and used `devtools::use_travis` and depended on `matrixStats` using `Imports`.  

The build log is located at https://travis-ci.org/muschellij2/testmatrixstats, but the main error (on Travis) is:
```
3.10s$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = TRUE);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
trying URL 'https://cloud.r-project.org/src/contrib/matrixStats_0.50.2.tar.gz'
Content type 'application/x-gzip' length 167570 bytes (163 KB)
==================================================
downloaded 163 KB
Installing matrixStats
Error: ‘BiocInstaller’ must be installed for this functionality.
Execution halted
```

**Comment by muschellij2** [comment]
Dug a little deeper and realized that when `biocViews` are in the description, `devtools` has the following line in https://github.com/hadley/devtools/blob/master/R/utils.r:
```r
is_bioconductor <- function(x) {
  x$package != "BiocInstaller" && !is.null(x$biocviews)
}
```
Thus, although not an `Imports` or `Suggests`, `biocInstaller` seems to be a hidden/implicit dependency when installing using `devtools`.  This affects Travis builds.  I will close the comment on travis-ci/travis-ci#6267, but leave it open here an open one on `devtools`.

**Comment by HenrikBengtsson** [comment]
Hi and thanks for this report and troubleshooting.  This seems somewhat familiar to me, but I don't remember how and when I bumped into this in the past.  I'm not sure if I ever got around to comment on `devtools:::is_bioconductor()` or it fell off my radar too soon.

Either way, since I cannot recall why I kept `biocViews: Infrastructure, Statistics` (there was a connection to Bioconductor in the past), I decided to just drop it for simplicity.  I've committed this to the develop branch of matrixStats, cf. commit f0bbef9.

**Comment by muschellij2** [comment]
It seems as though that `biocViews: Infrastructure, Statistics` was added somehow in your different commits - FYI.

**Comment by HenrikBengtsson** [comment]
Correct, it went into the [`develop`](https://github.com/HenrikBengtsson/matrixStats/tree/develop) branch.

I'm planning to submit this to CRAN around [October 7](https://github.com/HenrikBengtsson/matrixStats/issues/80#issuecomment-246809587).  Until that code is publicly released on CRAN, you either have to install that from GitHub (HenrikBengtsson/matrixStats@develop), or, which is probably safer, to install BiocInstaller from Bioconductor.

FYI, I use the 'git flow' workflow, where the `master` branch is the most recent stable release and identical to what's on CRAN, which currently matrixStats 0.50.2. The `develop` branch, which has matrixStats 0.50.2-9000, contains (fairly stable) work in progress and will be part of the next public release.

Hope this clarifies it.

**Comment by muschellij2** [comment]
Understood - thanks for the update.

Thanks
John

John
