### ISSUE TITLE
WISH: rowPaste, colPaste

### ISSUE THREAD

**Issue by mayer79** [HenrikBengtsson/matrixStats#93]
Thank you for this excellent package. It is extremely helpful.

Recently, I am frequently using "paste" to glue together all non-empty/non-NA entries per row. The naive approach using `apply` is extremely slow:
```
 apply(iris[1:5, 1:3], 1, function(z) paste0(z[!is.na(z) & z != ""], collapse = "\n"))
```
So I wonder if something like this would fit in your package? Useful arguments would be `sep` (-> collapse in the line above) and maybe whether to exclude "NA" and/or empty strings. So if one row consists of NA, "1", "", then a nice result of rowPaste would be "1" instead of "NA;1;".

**Comment by HenrikBengtsson** [comment]
Thanks - glad you it.

Thanks for the suggest.  However, I don't think string processing fits the overall objectives of matrixStats, which targets data types `integer`, `numeric` and somewhat `logical` too.  From an implementation point of view, these are directly translated to corresponding native-code (C) data types.  R strings, however, are a completely different type of creatures.  Not only do they vary in lengths (whereas numbers have a fixed-byte size), but they may also carry different encodings.  To handle the latter is a major challenge, at least if done with native code (cf. cran.r-project.org/web/packages/stringi).  Also, if support for strings would be added, I don't think there would an end to features one could add.

To conclude, handling of strings is outside the scope of this package.  I think that would better be done in a separate package.

**Comment by mayer79** [comment]
Good points, thanks for the explanation.
